#!/bin/bash

echo "Welcome to gem5 auto-installer"

#cloning gem5 repo to get source code
git clone https://gem5.googlesource.com/public/gem5

#move gem5 dir to the installing path
sudo mv gem5 /opt/gem5

echo "Working Direcotory Changed to"
#change working directory
cd /opt/gem5
pwd

#build-flag if typed enable the script to build a particular architecture
if [ $1 = "-b" ]; then
    #installs dependences to build the specified architecture simulatori
    echo "Installing dependencies..."
    sudo apt-get install -y build-essential git m4 scons zlib1g \
            zlib1g-dev libprotobuf-dev protobuf-compiler \
            libprotoc-dev libgoogle-perftools-dev python-dev python
    #build the architecture subsystem using scons
    sudo scons build/$2/gem5.opt
fi

